on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    if:  startsWith(github.head_ref, 'deploy/')
    steps:
      - name: Enable auto-merge for Deploy PRs
        run: gh pr merge --auto --merge --subject "$PR_MESSAGE [skip ci]" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_MESSAGE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
