on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/muchobien/ownda-api
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,suffix=,format=short
            type=edge,branch=main
      
      - name: Get short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update image tag
        uses: fjogeleit/yaml-update-action@main
        with:
          createPR: true
          commitChange: true
          targetBranch: main
          masterBranchName: main
          valueFile: docker-compose.yml
          propertyPath: services.ownda.image
          branch: deploy/${{ steps.short.outputs.sha }}
          message: 'chore(ci): deploy ${{ steps.short.outputs.sha }}'
          value: 'ghcr.io/muchobien/ownda-api:${{ steps.short.outputs.sha }}'
